version: "3"

env:
  LOCAL_URL: "http://localhost:8000/invoke"

tasks:
  invoke-local:
    desc: Invoke the local server
    cmds:
      - echo "Invoking local server at ${LOCAL_URL}"
      - >
        curl -X POST ${LOCAL_URL} 
        -H "Content-Type: application/json" 
        -d '{"query": "text"}'


